# Generated by Django 4.1 on 2022-08-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220820_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
